# Setup
title:               IFT6758 Project
tagline:             'A blog about an NHL data analysis'
description:          'A detailed report about the data analysis made over the last 5 NHL seasons. Made by <a href="https://github.com/J-bytes" target="_blank">Jonathan Beaulieu-Edmond</a>,  <a href="https://github.com/baril-jf" target="_blank">Jean-François Baril</a> and <a href="https://github.com/Seeeeeyo" target="_blank">Selim Gilon</a>.'
domain: Seeeeeyo.github.io
url: https://Seeeeeyo.github.io
baseurl: /nhl-games-prediction.github.io/
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Jean-François Baril
  url:               https://www.linkedin.com/in/bariljf/
  email:             bariljeanfrancois@gmail.com
  
author:
  name:              Jonathan Beaulieu-Edmond
  url:               https://www.linkedin.com/in/bariljf/
  email:             joe199827@gmail.com

author:
  name:              Selim Gilon
  url:               https://www.linkedin.com/in/selim-gilon/
  email:             selimgilon@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
